name: Hiest
version: 0.0.1
main: com.censkh.hiest.Hiest
depend: [WorldGuard]

commands:
 admin:
      description: Admin commands.
      usage: /<command>
      permission: hiest.admin
      permission-message: You don't have that permission.