name: Hiest
version: 0.0.1
main: com.censkh.hiest.Hiest

commands:
 nvps:
      description: .
      usage: /<command>
      permission: nvps
      permission-message: You don't have that permission.